baseurl = "/"
title = "Jerome Brette's Blog"
languageCode = "en-us"
paginate = "20" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Jerome Brette"
  bio = "Jerome Brette's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  subtitle = "Just another site" # Subtitle of your site
  description = " Jerome Brette's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  leftsidebar = false # Move sidebar to the left side if true
  authorbox = true
  post_navigation = true
  postSections = ["posts"]

[Params.widgets]
  search = true # Enable "Search" widget
  recent_articles = true # Enable "Recent arcticles" widget
  categories = true # Enable "Categories" widget
  tags = true # Enable "Tags" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
